---
title: "Best Models"
author: "Katriona Goldmann"
date: "8/19/2021"
output: 
 html_document: 
  code_folding: hide
  toc: yes
  toc_float:
      toc_collapsed: true
---

```{r setup, include=FALSE}
library(ggplot2)
library(kableExtra)
library(plotROC)
library(pROC)
library(caret)
library(ggpubr)
library(DT)
library(rmarkdown)
library(tidyr)
library(dplyr)
library(gbm)

knitr::opts_chunk$set(echo = TRUE, cache=FALSE, fig.width=14, 
                      fig.height=10, warning = FALSE)
```


# Scripts

```{r}
# Function to summarize models in a table
model_tabels <-function(model_list, drug){
  o = try(nested_rocs(model_list, metric="CDAI50",  drug=drug, filtering = "", k=FALSE))
  
  o2 = o$stats_df
  
  o2$Stat = gsub('[[:digit:]]+', '', rownames(o2))
  o2$Stat[o2$Stat == "F"] = "F1"
  
  o2 = o2 %>%
    gather(key = "Set", value = "value", "Test Stats", "Left-out Stats", "Overall Stats" ) %>%
    mutate(drug = unlist(lapply(strsplit(as.character(model), "_"), "[[", 2)),
           model = unlist(lapply(strsplit(as.character(model), "_"), "[[", 4)))
  
  o3 = o2 %>% group_split(Stat)
  names(o3) = levels(factor(o2$Stat))
  
  o4 = do.call(cbind, o3)
  o4 = o4[, ! grepl("model|Stat|Set|filtering|drug", colnames(o4))]
  o4 = cbind(o3[[1]][, c("model","Set",  "drug")], o4)
  colnames(o4) = gsub("\\.value", "", colnames(o4))
  o4 = o4[order(o4$AUC, decreasing = T), ]
  
  print(kable(o4[o4$Set == "Test Stats",  
                 c('model', 'drug', 'AUC', 'Accuracy',
                   'Balanced Accuracy', 'F1', 'Kappa',
                   'McnemarPValue', 'Precision', 'Prevalence',
                   'Recall', 'Sensitivity', 'Specificity')], row.names = F) %>% 
          kable_styling() %>% scroll_box(width = "100%"))
}

# Function to output plots of interest for a given model
outputs <- function(model){
  
  cat("\n\n\n\n</br></br>")  
  cat("\n\n\n\n\n\n ### Model Summary\n")
  
  
  cat(paste0("\n\n\U2022 Number of features in each fold: ", 
             paste(lapply(model$models, function(x) length(x$selected_features)), 
                   collapse=", ")))
  cat(paste("\n\n\U2022 Average test AUC on outer folds <b>", 
            format( model$auc, digit=3), "</b>"))
  cat(paste("\n\n\U2022 Average balanced accuracy on outer folds <b>",
            format(mean(model$df$Balanced.Accuracy), digit=3), "</b>\n\n\n"))
  
  all_folds = do.call(rbind, lapply(model$models, function(x) x$prob))
  total_auc = auc(all_folds$observed, all_folds$R, levels=c("NR", "R"), direction="<")
  cat(paste("\n\n\U2022 AUC on all test-set predictions from all outer folds<b>", format(total_auc, digits=3), "</b>\n\n"))
  
  
  inner_folds = do.call(rbind, lapply(model$models, function(x) {
    rfFit = x$fit
    accuracy_lo = rfFit$results
    lo_df = rfFit$pred
    for(colu in colnames(rfFit$bestTune)){
      accuracy_lo = accuracy_lo[accuracy_lo[, colu] == rfFit$bestTune[, colu], ]
      lo_df = lo_df[lo_df[, colu] == rfFit$bestTune[, colu], ]
    }
    return(lo_df)
  }))
  inner_auc = auc(inner_folds$obs, inner_folds$R, levels=c("NR", "R"), direction="<")
  cat(paste("\n\n\U2022 AUC on all left-out-set predictions from all outer folds<b>", 
            format(inner_auc, digits=3), "</b>\n\n"))
  
  
  cat("\n\n\n\n\n\n ### ROC curves\n")
  
  po = ggplot(all_folds, aes(d = observed, m = R)) +
    geom_roc(labels=F, pointsize=0, linemitre=1, color="dodgerblue") +
    geom_abline(slope=1, intercept=0, color="grey60", linetype="dashed") + 
    labs(x="1 - Specificity", y="Sensitivity", title = "Test Set") + 
    annotate("text", x=1, y=0.1,  hjust = 1, label=paste0("AUC = ", format(total_auc, digits=3))) + 
    theme_classic() + 
    theme(text = element_text(size=15))
  
  
  
  pi = ggplot(inner_folds, aes(d = obs, m = R)) +
    geom_roc(labels=F, pointsize=0, linemitre=1, color="gold2") +
    geom_abline(slope=1, intercept=0, color="grey60", linetype="dashed") + 
    labs(x="1 - Specificity", y="Sensitivity", title = "Left-Out Set") +
    annotate("text", x=1, y=0.1,  hjust = 1, label=paste0("AUC = ", format(inner_auc, digits=3))) + 
    theme_classic() + 
    theme(text = element_text(size=15))
  
  print(ggarrange(po, pi, ncol=2, nrow=1))
  
  # Interogate the feature data
  feat = data.frame(table(unlist(lapply(model$models, function(x) x$selected_features))))
  feat = feat[order(feat$Freq, decreasing = T), ]
  feat = feat[feat$Freq > 1, ]
  
  
  mod=model$models
  
  bestTune = do.call(rbind, lapply(mod, function(x) x$fit$bestTune))
  
  
  cat("\n\n\n ### Best Tuned Parameters\n")
  rownames(bestTune) = paste("Fold", 1:nrow(bestTune))
  
  bestTune = rbind(bestTune, "Average"=apply(bestTune, 2, mean))
  
  print(kable(bestTune) %>% kable_styling())
  
  
  tvst <- data.frame(clin_exp[, unique(unlist(lapply(model$models, function(x) x$selected_features)))])
  
  ## add response variable
  tvst$resp = factor(clinical$CDAI50_toc_resp, labels=c("NR", "R"))
  tvst = tvst[! is.na(tvst$resp), ]
  
   # train and fit on entire data set
  train_control <- trainControl(method="none",
                                classProbs = TRUE,
                                savePredictions = TRUE, 
                                number=1, 
                                repeats = 1)
  
  
  # no filtering for clinical & histology
  subdata = tvst
  subdata = subdata[complete.cases(subdata), ]
  
  # degree must be an integer
  if("degree" %in% colnames(bestTune)){
    bestTune["Average", "degree"] = round(mean(bestTune[rownames(bestTune) != "Average", "degree"]))
  }
  
  # fit on full data set
  fit <- caret::train(resp ~.,
                      data=subdata,
                      method = mod[[1]]$fit$method,
                      metric = "Accuracy",
                      trControl = train_control,
                      tuneGrid = bestTune["Average", , drop=F],
                      preProcess=NULL)

  vi = varImp(fit)
  vi =  data.frame(as.matrix(vi$importance))
  colnames(vi)[1] = "Overall"
  vi$gene = rownames(vi)
  vi = vi[order(abs(vi$Overall), decreasing = T), ]
  
  cat("\n\n ### Variable Importance \n")
  print(kable(vi[, c("gene", "Overall")],#, "Type", "Associated_diseases")], 
              row.names = F) %>% 
          kable_styling() %>% scroll_box(height = "400px"))
  vi = vi[vi$Overall != 0, ]
  
  #if(nrow(vi) > 50) vi = vi[1:50, ]
  vi$gene = factor(vi$gene, levels=rev(unique(vi$gene)))
  
  p1 =  ggplot(vi, aes(y=Overall, x=gene)) +
    geom_bar(stat="identity", fill="midnightblue") +
    coord_flip() +
    labs(y="Importance", x="") +
    theme_classic() + 
    theme(text=element_text(size=20), 
          legend.position="none", 
          panel.grid = element_line(colour = "grey92"),
          panel.grid.minor = element_line(size = rel(0.5)), 
          panel.grid.major = element_line(size = rel(0.7))) 
  print(ggarrange(ggplot(data=NULL) + theme_void(), p1, ncol=3, widths=c(1, 2, 1)))
  
  if(mod[[1]]$fit$method == "glmnet"){
    cat("\n\n ### Coefficients \n")
    
    tmp_coeffs <- coef(fit$finalModel, s = fit$bestTune$lambda)
    
    coefs = data.frame(as.matrix(tmp_coeffs))
    colnames(coefs)="coef"
    coefs$gene = rownames(coefs)
    coefs = coefs[order(abs(coefs$coef), decreasing = T), ]
    cat(paste("<b>Number of features following sparcity filter: ", 
              length(which(coefs$coef != 0)), "</b>\n\n"))
    
    coefs[coefs == 0] = "."
    
    
    
    print(kable(coefs, row.names = F) %>% kable_styling() %>% scroll_box(height = "400px"))
    
    
    coefs[coefs == "."] = 0
    #if(nrow(coefs) > 50) coefs = coefs[1:50, ]
    coefs$gene = factor(coefs$gene, levels=rev(unique(coefs$gene)))
    
    coefs$dir = sign(as.numeric(coefs$coef))
    
    p2 = ggplot(coefs, aes(y=as.numeric(coef), x=gene, fill=factor(dir))) +
      geom_bar(stat="identity") +
      scale_fill_manual(values=c("1"="midnightblue", "-1"="firebrick1", "0"="grey60")) + 
      coord_flip() +
      labs(y="Coefficient", x="") +
      theme_classic() + 
      theme(text=element_text(size=20), 
            legend.position = "none",
            panel.grid = element_line(colour = "grey92"),
            panel.grid.minor = element_line(size = rel(0.5)), 
            panel.grid.major = element_line(size = rel(0.7)))  
    
    
    print(ggarrange(ggplot(data=NULL) + theme_void(), p2, ncol=3, widths=c(1, 2, 1)))
  } else{p2 = ggplot(data=NULL) + theme_void()}
  
  return(list("test_roc"=po, "lo_roc"=pi, "variable_importance"=p1, "coefficients"=p2, "fit"=fit))
}
```



# Final Timepoint

```{r}
load("/media/gcpeac/R4RA_machine_learning/Data/curated_input.rdata")
source("/media/gcpeac/R4RA_machine_learning/4_Plotting_scripts/plotting_scripts.r")

files = list.files("/media/lvm1/R4RA_ML_outputs", #/input_2628", #¢R4RA_ML/Nested/", 
                   pattern="all_visit9_clin_hist_", full.names = T, recursive = T)

l = length(strsplit(files[1],"/")[[1]])

for(x in files) {
  load(x)
  obj = ls(pattern="t_clin")
  for(y in obj){ assign(x=paste0(gsub("t_clin", "x_clin", y)), get(y)) }
  rm(list=obj)
}

data=ls(pattern="x_clin")

t_nested = lapply(data, get)
rm(list=ls(pattern="x_clin"))

t_nested = unlist(t_nested, recursive=F)
paste("Removing", length(which(unlist(lapply(t_nested, class)) == "try-error")), "models which failed")

t_nested = t_nested[unlist(lapply(t_nested, class)) != "try-error"]
names(t_nested) <- unlist(lapply(1:length(t_nested), function(x){
  paste0(t_nested[[x]]$models[[1]]$metric, "_", as.character(t_nested[[x]]$models[[1]]$df$model))
}))

l = length(unlist(strsplit(names(t_nested)[1], "_")))

drugs = unique(unlist(lapply(names(t_nested), function(x) unlist(strsplit(x, "_"))[2])))

gc(verbose=F)
```



## Best TOC model 


```{r, results='asis'}
model_tabels(t_nested, "toc")
```

## TOC RF {.tabset .tabset-fade}

```{r, results='asis'}
out_toc=outputs(t_nested$CDAI50_toc_resp_svmRadial)
```


## {.toc-ignore}

## Best RTX Model 


```{r, results='asis'}
model_tabels(t_nested, "rtx")
```

## RTX svmRadial {.tabset .tabset-fade}

```{r, results='asis'}
out_rtx=outputs(t_nested$CDAI50_rtx_resp_svmRadial)
```


## {.toc-ignore}

## Best Refractory Model 

```{r, results='asis'}
model_tabels(t_nested, "any")
```

## Refractory RF {.tabset .tabset-fade}

```{r, results='asis'}
out_any=outputs(t_nested$CDAI50_any_resp_rf)
```

## {.toc-ignore}


## Final Figure

```{r, fig.height=18}

# function to create dummy facets, ggplot2 style
bio_facet = function(text, colour="grey80", outline_colour="white", outline_width=5,  
                     font_colour="black", angle=90, align="center", size=5){
  p = ggplot(df=NULL)  + 
    theme_void() + 
    annotate("text", x=0, y=1, label=text, angle=angle, colour=font_colour, size=size) + 
    theme(panel.background=element_rect(fill=colour, color=outline_colour, size=outline_width))
  if(align == "left") p = p + lims(x=c(0, 1))
  if(align == "right") p = p + lims(x=c(-1, 0))
  return(p)
}

# model names
names = c("gbm"="Gradient Boosting \nMachine", "rf"=" \nRandom forest", 
          "glmnet"="Lasso and Elastic-Net \nGeneralized Linear Model", 
          "svmRadial"="Radial Support\nVector Machine")

# plot theme
theme_tr =  theme(plot.title = element_text(hjust = 0.5, size=14), 
                  axis.title = element_text(size=12))

plot.list = list(
  # titles
  bio_facet(text = "", colour="white", angle=0), 
  bio_facet(text = "Rituximab", angle=0, size=7), 
  bio_facet(text = "Tocilizumab", angle=0, size=7), 
  bio_facet(text = "Refractory", angle=0, size=7),
  
  # Plots  
  bio_facet(text = "Test ROC", size=7), 
  out_rtx[[1]]+ labs(title=names[out_rtx$fit$method]) + theme_tr, 
  out_toc[[1]]+ labs(title=names[out_toc$fit$method]) + theme_tr, 
  out_any[[1]]+ labs(title=names[out_any$fit$method]) + theme_tr, 
  bio_facet(text = "Left-Out ROC", size=7), 
  out_rtx[[2]]+ labs(title=NULL) + theme_tr, 
  out_toc[[2]]+ labs(title=NULL) + theme_tr, 
  out_any[[2]]+ labs(title=NULL) + theme_tr, 
  bio_facet(text = "Variable Importance", size=7), 
  out_rtx[[3]]+ labs(title=NULL) + theme_tr+theme(axis.text=element_text(size=12)), 
  out_toc[[3]]+ labs(title=NULL) + theme_tr+theme(axis.text=element_text(size=12)), 
  out_any[[3]]+ labs(title=NULL) + theme_tr+theme(axis.text=element_text(size=12)))


p = ggarrange(plotlist = plot.list, ncol=4, nrow=4, #align="hv",
              widths=c(0.15, 1, 1, 1), heights=c(0.15,  1.2, 1, 1.5))


v=(0.15+1.2+1+1.5) / (0.15+1.2+1+1.8)

cairo_pdf("/media/gcpeac/R4RA_machine_learning/Data/final_fig_clin.pdf", height=0.8*0.8*v*1.7*11.75, width=0.8*1.7*8.25)
p
dev.off()

p
```




# Initial Timepoint

```{r}
load("/media/gcpeac/R4RA_machine_learning/Data/curated_input.rdata")
source("/media/gcpeac/R4RA_machine_learning/4_Plotting_scripts/plotting_scripts.r")

files = list.files("/home/kgoldmann/Documents/R4RA_ML/Nested/",
                   pattern="all_visit7_clin_hist_", full.names = T, recursive = T)

l = length(strsplit(files[1],"/")[[1]])

for(x in files) {
  load(x)
  obj = ls(pattern="t_clin")
  for(y in obj){ assign(x=paste0(gsub("t_clin", "x_clin", y)), get(y)) }
  rm(list=obj)
}

data=ls(pattern="x_clin")

t_nested_bl = lapply(data, get)
rm(list=ls(pattern="x_clin"))

t_nested_bl = unlist(t_nested_bl, recursive=F)
paste("Removing", length(which(unlist(lapply(t_nested_bl, class)) == "try-error")), "models which failed")

t_nested_bl = t_nested_bl[unlist(lapply(t_nested_bl, class)) != "try-error"]
names(t_nested_bl) <- unlist(lapply(1:length(t_nested_bl), function(x){
  paste0(t_nested_bl[[x]]$models[[1]]$metric, "_", as.character(t_nested_bl[[x]]$models[[1]]$df$model))
}))

l = length(unlist(strsplit(names(t_nested_bl)[1], "_")))

drugs = unique(unlist(lapply(names(t_nested_bl), function(x) unlist(strsplit(x, "_"))[2])))

gc(verbose=F)
```



## Best TOC model 


```{r, results='asis'}
model_tabels(t_nested_bl, "toc")
```

## TOC RF {.tabset .tabset-fade}

```{r, results='asis'}
out_toc_bl=outputs(t_nested_bl$CDAI50_toc_resp_glmnet)
```


## {.toc-ignore}

## Best RTX Model 


```{r, results='asis'}
model_tabels(t_nested_bl, "rtx")
```

## RTX svmRadial {.tabset .tabset-fade}

```{r, results='asis'}
out_rtx_bl=outputs(t_nested_bl$CDAI50_rtx_resp_svmRadial)
```



## {.toc-ignore}

```{r, fig.height=18}
roc_ci <- function(roc_plot, ci=0.9){
  obs_name = ifelse("observed" %in% colnames(roc_plot$data), "observed", "obs")
  rc = roc(response=roc_plot$data[, obs_name], predictor=roc_plot$data$R, direction="<")
  
  ci.obj <- cbind(ci.sp(rc, sensitivities = rc$sensitivities, boot.n=100, conf.level=ci), 
                  ci.se(rc, specificities = rc$specificities, boot.n=100, conf.level=ci))
  ci.df = data.frame(ci.obj)
  colnames(ci.df) = c("sp.low", "sp.median", "sp.high", 
                      "se.low", "se.median", "se.high")
  ci.df$y = rc$sensitivities
  ci.df$x = rc$specificities
  
  # To report the CI on the AUC (can be a bit much for plots)
  #auc = as.character(format(ci.auc(rc, conf.level=ci), digits=3))
  #roc_plot$layers[[3]]$aes_params$label = paste0("AUC = ", auc[2], " (", auc[1], "-", auc[3], ")")
  
  roc_plot + 
    geom_ribbon(data=ci.df, aes(x=1-x, xmin=1-sp.high, xmax=1-sp.low, 
                    y=y, ymin=se.high, ymax=se.low), 
                alpha=0.1, inherit.aes = F) 
}


plot.list = list(
  # titles
  bio_facet(text = "", colour="white", angle=0), 
  bio_facet(text = "Rituximab", angle=0, size=7), 
  bio_facet(text = "Tocilizumab", angle=0, size=7), 
  bio_facet(text = "Refractory", angle=0, size=7),
  
  # Plots  
  bio_facet(text = "Test ROC", size=7), 
  roc_ci(out_rtx_bl[[1]]) + labs(title=names[out_rtx_bl$fit$method]) + theme_tr, 
  roc_ci(out_toc_bl[[1]]) + labs(title=names[out_toc_bl$fit$method]) + theme_tr, 
  roc_ci(out_any[[1]]) + labs(title=names[out_any$fit$method]) + theme_tr, 
  bio_facet(text = "Left-Out Inner Fold ROC", size=7), 
  roc_ci(out_rtx_bl[[2]]) + labs(title=NULL) + theme_tr, 
  roc_ci(out_toc_bl[[2]]) + labs(title=NULL) + theme_tr, 
  roc_ci(out_any[[2]]) + labs(title=NULL) + theme_tr, 
  bio_facet(text = "Variable Importance", size=7), 
  out_rtx_bl[[3]]+ labs(title=NULL) + theme_tr+theme(axis.text=element_text(size=12)), 
  out_toc_bl[[3]]+ labs(title=NULL) + theme_tr+theme(axis.text=element_text(size=12)), 
  out_any[[3]]+ labs(title=NULL) + theme_tr+theme(axis.text=element_text(size=12))
)

w = 1.7*8.25
h = 0.8*1.7*11.75
hs = c(0.15, 1, 1, 1.8)
hs = hs/sum(hs)
y = hs[1]*h/w
ws = c(y, 1/(y+3), 1/(y+3), 1/(y+3))

p =  ggarrange(plotlist = plot.list, ncol=4, nrow=4, widths=ws, heights=hs)

cairo_pdf("/media/gcpeac/R4RA_machine_learning/Data/Initial_resp_clinical_fig_with_ci.pdf", 
          height=0.8*1.7*11.75, width=1.7*8.25)
p
dev.off()

p


save("/media/gcpeac/R4RA_machine_learning/Data/clinical_histological_objects.rdata")
```

